# -*- coding: utf-8 -*-
"""PuliziaHollister.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AeMmQDAyk-RtabPh_Jj1ISPg5ayvZgBi

# Importazione pacchetti
"""

import pandas as pd
import re
import numpy as np
import os
import _string

"""# Importazione dataset"""

df = pd.read_csv(r'/Users/mattia/desktop/dati/Hollister.csv')
len(df)

"""# Rimozione NA 
Vengono rimossi tutti i vestiti dei quali non si conosce il materiale.
Questo perchè non ci servono a nulla dato che l'oggetto principale dello studio è il materiale dei vestiti.
"""

df=df.dropna(subset=["Materiali"]) #rimozione na 
df=df.reset_index()                #Settare di nuovo gli indici, va fatto sennò da errore.
len(df)

"""# Pulizia colori
Per una migliore interpretazione tutte le sfumature dei colori vengono attribuite ad un solo colore, ad esempio, corallo viene attribuito ad arancione.

## Creazione categorie di colori
"""

altro=["BACCA","STAMPA ZEBRATA","LAVAGGIO CHIARO CON VERNICE","LAVAGGIO MEDIO ACCESO CON STRAPPI",	"LAVAGGIO NERO CON STRAPPI",	"NERO SLAVATO CON STRAPPI",	"SCURO CON STRAPPI","LAVAGGIO CHIARO MEDIO STRAPPATO","CAMO","LAVAGGIO MEDIO CHIARO","STAMPA SCURA","LAVAGGIO MEDIO SCURO CON STRAPPI","DARK RINSE","NERO E CORALLO","VERDE E BLU NAVY","PIEGATURA NERA","LAVAGGIO MEDIO CON CINTURA","LIGHT DESTROYED WASH","LAVAGGIO CHIARO DISTRUTTO","MEDIO","LAVAGGIO MEDIO A RIGHE","LAVAGGIO MEDIO CON STRAPPI EFFETTO FLOREALE","TEAL PATTERN","DARK RIPPED WASH","LAVAGGIO MEDIO CON STRAPPI SULLE GINOCCHIA","RINSE SCURO","DISTRUTTO CHIARO","LAVAGGIO MEDIO DISTRUTTO","LAVAGGIO CHIARO MEDIO","CHIARO","LAVAGGIO MEDIO SCURO","RINSE LEGGERMENTE STRAPPATI","DISTRUTTO SCURO",	"LAVAGGIO MEDIO CON STRAPPI",	"CHIARO DISTRUTTO","	LAVAGGIO MEDIO STAMPATO",	"LAVAGGIO SCURO",	"CHIARO SBIADITO E FONDO SEMPLICE",	"LAVAGGIO SCURO CON STRAPPI","LAVAGGIO MEDIO CON RAMMENDI",	"LAVAGGIO GRIGIO CON STRAPPI","	LAVAGGIO NERO","SCURO","DISTRUTTO SCURO CON FONDO SFRANGIATO","MEDIA","MEDIO CON RAMMENDI","LAVAGGIO MEDIO CON STRAPPI SCURO","LAVAGGIO CHIARO","MEDIO DISTRUTTO","LAVAGGIO MEDIO","LAVAGGIO SCURO MEDIO","LAVAGGIO CHIARO CON STRAPPI","RINSE","A FIORI ARANCIONI","MULTI RIGHE","NERO SLAVATO - STEP BROTHER","MULTI LOGO","BLU E BIANCO","BLACK AND GREEN","BEIGE E NERO","BLU NAVY E BIANCO","MIX PRIDE","MULTI ICON","MULTICOLORE","MULTI","TIE-DYE MULTICOLORE"]

arancione=["CORALLO CON STAMPA","CORALLO ARANCIONE","ARANCIONE NEON","CORALLO CHIARO","ORANGE SPICE FLORAL","ARANCIONE BRUNITO","ARANCIONE SFUMATO","CORAL","LIGHT ORANGE","ARANCIONE A RIGHE","ARANCIONE CON MOTIVO","ARANCIONE SPEZIATO","ARANCIO","ARANCIONE CON STAMPA","ARANCIONE BRUNITO CON MOTIVO"]

beige=["BEIGE"]

bianco=["BIANCO CON ICONE","RIPPED WHITE","BIANCO DISTRUTTO","SCOZZESE BIANCO","BIANCO CON TEXTURE","BIANCO A QUADRI","BIANCO CON STAMPA","WHITE COLOR BLOCK","BIANCO FLOREALE","BIANCO WITH-TEXT","BIANCO SPORCO","BIANCO","MOTIVO BIANCO","BIANCO TESTURIZZATO","BIANCO A RIGHE"]

blu=["BLUE PRINT","MOTIVO BLU NAVY","BLU SHINE","BLU SCINTILLANTE","BLU NAVY CON STAMPA","AZZURRO CON STAMPA","SCOZZESE BLU","RINSE BLU SCURO","BLU SCURO A FIORI","RINSE BLU","QUADRI BLU","LIGHT BLUE PRINT","BLU A FIORI","BLU A RIGHE","MOTIVO BLU","MOTIVO AZZURRO","AZZURRO A FIORI","BLU CON STAMPA","BLU TIE-DYE","BLU","AZZURRO","BLU NAVY","BLU NAVY A RIGHE","BLU CHIARO A RIGHE","BLU SCURO","TINTURA AZZURRA","BLU NAVY FLOREALE","NAVY BLUE STRIPE"]

ciano=["TURCHESE CON STAMPA","TURCHESE"]

giallo=["KAKI CHIARO","MOTIVO CREMA","ICONA CREMA","GIALLO FLOREALE","GIALLO CON MOTIVO","CREMA","CREAM","SCOZZESE CREMA","GIALLO"]

grigio=["GRIGIO MEDIO UNIFORME","MOTIVO SCOZZESE GRIGIO SCURO","GRIGIO CON STAMPA","GRIGIO TIE-DYE","LAVAGGIO ACIDO GRIGIO CHIARO","SLATE","LAVAGGIO GRIGIO","LIGHT GREY SD/TEXTURE","GRIGIO CHIARO MÉLANGE","SCALA DI GRIGI","GRIGIO TALPA","GRIGIO","GRIGIO SCURO","GRIGIO MELANGE","GRIGIO CHIARO","GRIGIO SCURO CON TEXTURE","GREY PATTERN"]

marrone=["KAKI","MARRONE CON MOTIVO","MOTIVO MARRONE SCURO","MARRONE SCINTILLANTE","MARRONE CON STAMPA","MARRONE SCURO CON STAMPA","DARK BROWN FLORAL","BROWN PRINT","SCOZZESE MARRONE CHIARO","MARRONE CHIARO CON MOTIVO","SCOZZESE MARRONE SCURO","MARRONE CHIARO A RIGHE","SCOZZESE MARRONE","MARRONE SCURO A RIGHE","MARRONE CHIARO CON STAMPA","MARRONE SCURO DD","LIGHT BROWN","MARRONE SCURO","MARRONE CHIARO","CAMMELLO","RIGHE MARRONI","MARRONE","CLAY","MARRONE FLOREALE"]

nero=["RIPPED BLACK","NERO CON DUE BOTTONI","NERO CON STRAPPI","NERO DISTRUTTO","BLACK FLORAL","NERO CON MOTIVO","FADED BLACK","NERO SLAVATO","BLACK PLAID","NERO FLOREALE","NERO","NERO CON STAMPA","SCOZZESE NERO","NERO DÉLAVÉ","NERO DD"]

rosa=["ROSA SCURO CON MOTIVO","ROSA NEON","LIGHT PINK FLORAL","ROSA CON MOTIVO","ROSA CREMA","ROSA ACCESO","ROSA A RIGHE","ROSA A FIORI","ROSA FLOREALE","ROSA SCURO TIE-DYE","ROSA CON STAMPA","SCOZZESE ROSA","ROSA","ROSA SCURO","ROSA CHIARO","LIGHT PINK PRINT","PINK"]

rosso=["MOTIVO ROSSO","ROSA HOT","ROSSO CON STAMPA","PAPRIKA","ROSSO DD","ROSSO","ROSSO TERRACOTTA","ROSSO PAPRIKA"]

verde=["VERDE CHIARO CON MOTIVO","MINT PATTERN","MOTIVO MINT","VERDE CHIARO SCINTILLANTE","VERDE SCINTILLANTE","VERDE CON STAMPA","MOTIVO VERDE","VERDE OLIVA SCINTILLANTE","VERDE NEON","VERDE FLOREALE","VERDE MINT","VERDE CHIARO FLOREALE","GREEN FLORAL","VERDE OLIVA DD","VERDE OLIVA MIMETICO","VERDE MENTA","VERDE OLIVA CHIARO","VERDE MINT A FIORI","NEON GREEN","VERDE CHIARO SCOZZESE","MENTA","VERDE OLIVA TIE-DYE","VERDE CHIARO CON STAMPA","VERDE CHIARO A FIORI","VERDE CHIARO","VERDE A RIGHE","VERDE","GREEN DD","VERDE LIME","VERDE SCURO","VERDE OLIVA SCURO","LIGHT GREEN","SALVIA","SCOZZESE VERDE","VERDE OLIVA FLOREALE","OLIVE GREEN","VERDE OLIVA"]

viola=["VIOLA TIE-DYE","VIOLA CON MOTIVO","VIOLA CHIARO CON STAMPA","VIOLA","BORDEAUX","LIGHT PURPLE","BORDEAUX TIE-DYE"]

"""## Assegnazione colori"""

#Attribuzione dei colori
for i in range(0,len(df)):
  if df["Colore"][i].strip() in arancione: #1
    df["Colore"][i]="Arancione"

  elif df["Colore"][i].strip() in beige:  #2
    df["Colore"][i]="Beige"

  elif df["Colore"][i].strip() in bianco: #3
    df["Colore"][i]="Bianco"

  elif df["Colore"][i].strip() in blu: #4
    df["Colore"][i]="Blu"

  elif df["Colore"][i].strip() in ciano: #5
    df["Colore"][i]="Ciano"    

  elif df["Colore"][i].strip() in giallo: #6
    df["Colore"][i]="Giallo"

  elif df["Colore"][i].strip() in grigio: #7
    df["Colore"][i]="Grigio"

  elif df["Colore"][i].strip() in marrone: #8
    df["Colore"][i]="Marrone"

  elif df["Colore"][i].strip() in nero: #9
    df["Colore"][i]="Nero"

  elif df["Colore"][i].strip() in rosa: #10
    df["Colore"][i]="Rosa" 

  elif df["Colore"][i].strip() in rosso: #11
    df["Colore"][i]="Rosso"

  elif df["Colore"][i].strip() in verde: #12
    df["Colore"][i]="Verde"

  elif df["Colore"][i].strip() in viola: #13
    df["Colore"][i]="Viola"

  elif df["Colore"][i].strip() in altro: #14
    df["Colore"][i]="Altro"

  else:
    df=df.drop(i)



df=df.reset_index()    #si devono rimettere gli indici perchè alcune righe che presentano colori ambigui verranno eliminate

len(df)

"""# Pulizia materiali"""

materiali=df["Materiali"]     #Estrarre colonne
#Inizializzazione dataset
dataset = pd.DataFrame({'A' : []})

for i in range(0,len(materiali)):
  stringa=materiali[i]
##########################
  #Risolve eventuali problemi che gli na potrebbero dare skippandoli.
  #if str(stringa).lower() == "nan" or  str(stringa).lower() == "null" or str(stringa).lower() == "na" or str(stringa)=="" or str(stringa)==" ":
   # continue #RIMOSSA, preferisco dia errore, almeno mi accorgo che c'è ancora qualche NA
  if stringa[0].isdigit()==True: #risolve problemi su rappresentazioni di tipo (senza classe di riferimento)  : "59% cotone, 21% viscosa, 12% modal, 6% poliestere, 2% elastan"
            stringa= "Corpo:"+stringa
##########################  

  ma=re.findall(r":[\w,\s%]*",stringa) #rimozione della classe di appartenenza dei materiali.

  ma=" ".join(ma)                      #riportare tutto in una una stringa per lavorare meglio
 
  ma=re.findall(r"[a-zA-Z \s]{2,}",ma) #Estrazione nomi dei materiali 
  
  

  #Ulteriore pulizia dei nomi materiali
  for j in range(0,len(ma)):
    ma[j]=ma[j].strip().capitalize()  #toglie spazi iniziali e finali e mette prima lettera maiuscola e resto tutto minuscolo
    ma[j]=re.sub("[\s]","_",ma[j])    #Se una parola è doppia toglie lo spazio ed unisce con un trattino le due parole
    if ma[j]=="Poliestere_riciclato" or ma[j]=="Fibre_di_poliestere_riciclato":
      ma[j]="Poliestere"

    if ma[j]=="Rayon":
      ma[j]="Viscosa"
  ###################Fine ulteriore pulizia

  ma = list(dict.fromkeys(ma))        #Rimozione di eventuali materiali che compaiono più volte in diverse classi.
 
  vettore_uni=np.ones(len(ma))        #Vettori di uno per i materiali presenti 
  
  vettore_uni.astype(int)             #Togliere decimali dagli uno, nota: non sembra funzionare.
  
  riga= pd.DataFrame([vettore_uni], columns=ma)        #Crea la riga 
  
  dataset=pd.concat([dataset, riga])                   #Aggiunge la riga al dataset esistente


################### ################### ################### ################### ################### 
#LAVORARE SUL DATASET PANDAS CREATO

#Sostituzione degli na con degli zeri (0).
dataset=dataset.fillna(0) 

#Rimozione colonna inutile
dataset.drop(["A"], inplace=True, axis=1)

#Aggiustamento indici
dataset=dataset.reset_index()

#ORDINARE IL DATASET PER COLONNA :
dataset = dataset.reindex(sorted(dataset.columns), axis=1)  

#Creazione della colonna che fornisce il numero di fibre presenti nel vestito.
dataset['N.Fibre_Differenti'] = dataset.sum(axis=1)

#Rimozione colonna inutile
dataset.drop(["index"], inplace=True, axis=1)

#Aggiunta del nuovo dataset al vecchio.
dati=pd.concat([df, dataset], axis=1) #non ha senso farlo perchè il dataset in input non è corretto

"""# Esportazione dataset"""

dati.to_csv("/Users/mattia/desktop/P_Hollister.csv")




