# -*- coding: utf-8 -*-
"""PuliziaHM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgPR9l9D9PBZdvWN4akhrQkgVPr5mLDa

# Importazione pacchetti
"""

import pandas as pd
import re
import numpy as np
import os
import _string

"""# Importazione dati"""

df = pd.read_csv(r'/Users/mattia/desktop/dati/HM.csv')
len(df)

"""## Eliminazione NA"""

df=df.dropna() 
df=df.reset_index() 
len(df)

"""# Pulizia colori

### Altro
"""

#m=df["Colore"]
#a=m.drop_duplicates()
#a=a.dropna() 
#a=a.reset_index()

#a=a["Colore"].drop_duplicates()
#a=a.reset_index(drop=True)

"""## Liste colori"""

altro=["Ruggine","Black-coloured","Silver-coloured"]

arancione=["Dark orange","Arancione ruggine","Arancione mélange","Light orange","Orange marl","Arancione fiamma","Corallo chiaro","Apricot","Corallo","Albicocca","Arancione scuro","Arancione brillante","Albicocca chiaro","Orange","Arancione chiaro","Arancione"]
beige=["Sabbia","Beigeélange","Beige-de-poule","Beige nocciola","Powder beige","Beige cipria","Beige avena chiaro","Beige sabbia mélange","Light beige marl","Beige chiaro","Beige scuro-de-poule","Dark beige marl","Beige chiaro-de-poule","Beige-patterned","Beige mélange","Dark beige","Beige avena mélange","Beige avena mèlange","Beige avena melange","Light beige","Beige scuro","Beige","Beige chiaro","Beige scuro mélange","Beige scuro melange","Beige scuro mèlange","Beige chiaro mélange","Beige chiaro melange","Beige chiaro mèlange"]
bianco=["Bianco7 up","Biancoélange","Bianco","Bianco-cola","Bianco naturale mélange","Bianco mélange","White","Bianco-de-poule","Natural white","Bianco naturale","Bianco","White"]
blu=["Light blue-patterned","Blue-patterned","Azzurro","Azzurroélange","Blu scuroélange","Pigeon blue","Blu denim chiarissimo","Dark denim blue","Denim blue","Pale denim blue","Blu medio","Blu notte","Light denim blue","Blu petrolio scuro","Bright blue","Blu cobalto","Azzurro mélange","Blu ghiaccio","Blu mélange","Denim blue","Blu denim pallido","Blu tortora","Navy blue","Dark blue marl","Light blue","Blue","Dark blue","Blu fiordaliso","Blu denim scuro","Azzurro","Blu denim","Blu scuro","Blu","Blu acceso","Blu navy","Blu denim chiaro"]
ciano=["Dark turquoise","Ciano","Turchese chiaro","Turchese","Turquoise","Turchese scuro"]
ecru=["Ecru chiaro"]
giallo=["Crema'","Giallo neon","Giallo neon pallido","Crema","Crema-cola","Cream-patterned","Ocra","Dorato","Cream-dye","Giallo scuro","Yellow","Cream","Crema","Dark yellow","Light yellow","Giallo","Giallo senape","Giallo chiaro"]
grigio=["Greige chiaro mélange","Grigio scuroélange","Argento","Light greige","Dark greige","Grigio scuro-de-poule","Dark denim grey","Grey","Denim grigio scuro","Denim grey","Grigio denim","Grigio denim scuro","Dark grey marl","Talpa chiaro","Grigio mélange-cola","Grigio chiaro mél","Grigio mél","Light grey-blue","Grey marl","Grigio ghiaccio","Light grey marl","Grigio antracite","Greige scuro mélange","Dark grey","Greige marl","Light grey","Greige mélange","Talpa scuro","Grigio scuro mélange","Grigio melange","Grigio mélange","Grigio mèlange","Talpa","Grigio fumo","Greige chiaro","Greige scuro","Greige","Grigio scuro","Argentato","Grigio chiaro","Grigio","Grigio chiaro melange","Grigio chiaro mélange","Grigio chiaro mèlange"]
marrone=["Dark brown marl","Marrone scuroélange","Marrone scuro mélange","Rust brown","Marrrone","Marrone","Marrone quadri","Marrone ruggine","Marrone cioccolato","Light brown","Marrone mélange","Mole","Brown","Dark brown","Marrone scuro","Marrone","Marrone chiaro"]
nero=["Nero1","Nero40 den","Nero20 den","Nero70 den","Nero100 den","Nero200 den","Denim nero","Nero-cola","Neroélange","Nero-de-poule","Nero mélange","Nero-block","Petrolio","Black-patterned","Nero","Black","Nero®"]
rosa=["Rosa nebbia chiaro","Rosa pallido","Rosa nebbia","Rosa cipria scuro","Rosa","Rosa chiaro","Rosaélange","Rosa chiaroélange","Rosa polvere","Rosa cipria chiaro","Powder pink","Rosa chiaroès jolie","Rosa pesca","Pink","Fucsia","Rosa chiaro mélange","Light pink-dye","Rosa scuro","Rosa antico scuro","Light pink","Old rose","Rosa acceso","Rosa chiaro","Rosa cipria","Rosa","Rosa antico"]
rosso=["Rosso's favorite","Rosso vivo","Rosso ruggine","Rosso fiammante","Cerise","Rosso scuro","Bright red","Ciliegia","Rosso","Rosso-cola","Rosso acceso","Red"]
verde=["Verde mélange","Lime green","Light neon green","Verde kaki ch.","Bright green","Neon green","Verde mentaélange","Verde polvere chiaro","Verde nebbia","Light khaki green","Verde polvere","Verde menta chiaro","Verde chiaro pallido","Verde chiaro mélange","Verde-beige","Khaki green","Verde oliva scuro","Dark khaki green","Olive green","Verde nebbia chiaro","Verde neon chiaro","Verde muschio","Verde salvia","Verde neon","Dark green","Verde lime","Verde pistacchio","Verde-beige chiaro","Verde kaki chiaro","Verde giallognolo chiaro","Light green","Verde kaki scuro","Verde salvia chiaro","Verde salvia scuro","Verde kaki","Green","Verde chiaro","Verde acceso","Verde","Verde scuro","Verde menta","Verde oliva"]
viola=["Plum purple","Malva","Malva chiaro","Viola'amicizia","Viola prugna scuro","Lavanda","Prugna","Viola chiaro mélange","Lilla","Erica chiaro","Purple","Light purple","Viola mélange","Viola prugna","Bordeaux scuro","Bordeaux","Viola pallido","Viola","Viola chiaro"]

"""## Pulizia"""

for i in range(0,len(df)):
  m=re.sub(r"/[\s a-zA-Z]*","",df["Colore"][i])
 
  m=re.sub(r"[^a-zA-Z \- \s]*","",m)
  m=m.strip()

  if m in arancione:
    df["Colore"][i]="Arancione"
  elif m in beige :
    df["Colore"][i]="Beige"

  elif m in  bianco :
    df["Colore"][i]="Bianco"
  
  elif m in blu:
    df["Colore"][i]="Blu"
  
  elif m in ciano:
    df["Colore"][i]="Ciano"
  elif m in ecru:
    df["Colore"][i]="Ecru"
  elif m in giallo:
    df["Colore"][i]="Giallo"
  elif m in grigio:
    df["Colore"][i]="Grigio"
  elif m in marrone:
    df["Colore"][i]="Marrone"
  elif m in nero:
    df["Colore"][i]="Nero"
  elif m in rosa:
    df["Colore"][i]="Rosa"
  elif m in rosso:
    df["Colore"][i]="Rosso"
  elif m in verde:
    df["Colore"][i]="Verde"
  elif m in viola:
    df["Colore"][i]="Viola"
  elif m in altro:
    df["Colore"][i]="Altro"
  else:
    df=df.drop(i)
df=df.reset_index()      #si devono rimettere gli indici perchè alcune righe che presentano colori ambigui verranno eliminate

len(df)

"""# Pulizia Materiali

## Settings
"""


m=df["Materiali"]

"""## Pulizia effettiva"""

dataset = pd.DataFrame({'A' : []})
for i in range(0,len(m)):
  if m[i]=="Null":
    #print("Eliminato")
    df=df.drop(i) #eliminare le righe che non hanno materiale
    continue 

  k=re.sub("[a-zA-Z\s]*:","",m[i]) #Restituisce solo i materiali con la corrispettiva percentuale
  #n=re.sub("[0-9%]*","",k)
  ma=re.findall(r"[a-zA-Z \s]{2,}",k)


  for j in range(0,len(ma)):
    ma[j]=ma[j].strip().capitalize()  #toglie spazi iniziali e finali e mette prima lettera maiuscola e resto tutto minuscolo
    ma[j]=re.sub("[\s]","_",ma[j])    #Se una parola è doppia toglie lo spazio ed unisce con un trattino le due parole
    
    if ma[j]=="Poliestere_riciclato" or ma[j]=="Fibre_di_poliestere_riciclato":
      ma[j]="Poliestere"
    
    elif  ma[j]=="Lana_di_yak" or 	ma[j]=="Lana_merinos":
      ma[j]="Lana"

    elif ma[j]=="Copoliestere":
      ma[j]="Poliestere"
    
    elif ma[j]=="Poliuretano_termoplastico":
      ma[j]="Poliuretano"
    
    elif ma[j]=="Rayon":
      ma[j]="Viscosa"


      
  ma = list(dict.fromkeys(ma))        #Rimozione di eventuali materiali che compaiono più volte in diverse classi.

  vettore_uni=np.ones(len(ma))        #Vettori di uno per i materiali presenti 
  
  vettore_uni.astype(int)             #Togliere decimali dagli uno, nota: non sembra funzionare.
  
  riga= pd.DataFrame([vettore_uni], columns=ma)        #Crea la riga 
  
  dataset=pd.concat([dataset, riga])   

################## ################### ################### ################### ################### 
df=df.reset_index(drop=True)    #si devono rimettere gli indici perchè alcune righe che presentano colori ambigui verranno eliminate
#LAVORARE SUL DATASET PANDAS CREATO

#Sostituzione degli na con degli zeri (0).
dataset=dataset.fillna(0) 

#Rimozione colonna inutile
dataset.drop(["A"], inplace=True, axis=1)

#Aggiustamento indici
dataset=dataset.reset_index()

#ORDINARE IL DATASET PER COLONNA :
dataset = dataset.reindex(sorted(dataset.columns), axis=1)  

#Creazione della colonna che fornisce il numero di fibre presenti nel vestito.
dataset['N.Fibre_Differenti'] = dataset.sum(axis=1)

#Rimozione colonna inutile
dataset.drop(["index"], inplace=True, axis=1)
dati=pd.concat([df, dataset], axis=1) #non ha senso farlo perchè il dataset in input non è corretto

#Rimozione colonna inutile
try:
    dati.drop(["Unnamed: 0","...1"], inplace=True, axis=1)
except:
    pass
try:
    dati.drop(["level_0"], inplace=True, axis=1)
except:
    pass


""" # Esportazione dati"""
#dataset.to_csv("/Users/mattia/desktop/materiali_HM.csv")
dati.to_csv("/Users/mattia/desktop/P_HM.csv")

